title: CSS Reference
subtitle: "免费的 CSS 属性可视化文档"
description: "CSS Reference is a free visual guide to CSS. It features the most popular properties, and explains them with illustrated and animated examples."
share: "CSS Reference: a free visual guide to the most popular CSS properties."
url: http://localhost:4000
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
